name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: simple-server:v1.0

      - name: Test
        run: |
          docker run -d --name simple-server -p 8080:8080 -e GREETING_NAME=Alex simple-server:v1.0

          # wait for container ready
          sleep 30

          greeting=$(curl -s http://localhost:8080)
          if [ "$greeting" != "Hello, Alex" ]; then
            echo "Expected [Hello, Alex], but greeting from docker [$greeting] doesn't macthes"
            exit 1
          fi